# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Tests"

on:
  pull_request:
  push:
    branches:
      - "master"

env:
  COMPOSER_ROOT_VERSION: "1.3.x-dev"

jobs:
  tests:
    name: "Tests"
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
        operating-system: [ ubuntu-latest ]
        composer-version:
          - "2.0"
          - "2.1"
          - "2.2"
          - "snapshot"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: "composer:${{ matrix.composer-version }}"

      - name: "Build PHAR"
        run: "php vendor/bin/box compile --config $(pwd)/box.json"
