# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Tests"

on:
  pull_request:
  push:


env:
  COMPOSER_ROOT_VERSION: "1.3.x-dev"

jobs:
  tests:
    name: "Tests"
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
        operating-system: [ ubuntu-latest, windows-latest ]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Print PHP version - should be ${{ matrix.php-version }}"
        run: "php bin.php"

      - name: "Install new PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.0"

      - name: "Print PHP version - should be 8.0"
        run: "php bin.php"

      - name: "Reinstall PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Print PHP version - should be ${{ matrix.php-version }}"
        run: "php bin.php"
